# Generated by Django 3.0.6 on 2020-05-17 19:45

from django.db import migrations
import tournaments.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', tournaments.models.UserManager()),
            ],
        ),
    ]
