# Generated by Django 3.0.6 on 2020-05-19 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_auto_20200519_1230'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='check_registration_deadline',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.BinaryField(editable=True),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(registration_deadline__gt=datetime.datetime(2020, 5, 19, 17, 58, 10, 365218)), name='check_registration_deadline'),
        ),
    ]
