# Generated by Django 3.0.6 on 2020-05-19 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_auto_20200519_1759'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='check_registration_deadline',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='images/3/'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(registration_deadline__gt=datetime.datetime(2020, 5, 19, 18, 27, 36, 546853)), name='check_registration_deadline'),
        ),
    ]
