# Generated by Django 3.0.6 on 2020-05-19 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_auto_20200519_1918'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='check_registration_deadline',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='tournament',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(registration_deadline__gt=datetime.datetime(2020, 5, 19, 17, 29, 31, 77664, tzinfo=utc)), name='check_registration_deadline'),
        ),
    ]
