# Generated by Django 3.0.6 on 2020-05-19 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_auto_20200519_1929'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='check_registration_deadline',
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='images/3/'),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(registration_deadline__gt=datetime.datetime(2020, 5, 19, 17, 32, 21, 915314, tzinfo=utc)), name='check_registration_deadline'),
        ),
    ]
