# Generated by Django 3.0.6 on 2020-05-19 20:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tournaments.models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_auto_20200519_1932'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='check_registration_deadline',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournaments.Tournament'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to=tournaments.models._upload_to),
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(registration_deadline__gt=datetime.datetime(2020, 5, 19, 20, 11, 6, 627415, tzinfo=utc)), name='check_registration_deadline'),
        ),
    ]
