# Generated by Django 3.0.6 on 2020-05-20 18:32

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_auto_20200520_2022'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournament',
            name='check_registration_deadline',
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(registration_deadline__gt=django.db.models.functions.datetime.Now()), name='check_registration_deadline'),
        ),
    ]
