# Generated by Django 3.0.6 on 2020-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_auto_20200520_2032'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('tournament_id', 'user_id'), name='one registration per user'),
        ),
    ]
