# Generated by Django 3.0.6 on 2020-05-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_auto_20200520_2252'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(check=models.Q(ranking__gt=0), name='positive ranking'),
        ),
    ]
