# Generated by Django 3.0.6 on 2020-05-21 12:00
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_auto_20200521_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.now),
            preserve_default=False,
        ),
    ]
