# Generated by Django 3.0.6 on 2020-05-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='number',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
