# Generated by Django 3.0.6 on 2020-06-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0023_auto_20200521_1559'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(check=models.Q(max_number_of_participants__gt=1), name='at least 2 participants'),
        ),
    ]
